In [5]:
!pip install faker

^C
Collecting faker
  Using cached faker-40.23.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: tzdata in c:\users\kuldeep\anaconda3\lib\site-packages (from faker) (2025.2)
Using cached faker-40.23.0-py3-none-any.whl (2.0 MB)
Installing collected packages: faker
Successfully installed faker-40.23.0

In [6]:
import pandas as pd
import numpy as np
import os
from faker import Faker
from random import randint, choice, uniform
from datetime import datetime, timedelta

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

In [7]:
# Root Project Folder
project_folder = "Executive_Assistant_Business_Dashboard"

# List of folders
folders = [
    "data",
    "reports",
    "charts",
    "output",
    "dashboard"
]

# Create root folder
os.makedirs(project_folder, exist_ok=True)

# Create subfolders
for folder in folders:
    os.makedirs(os.path.join(project_folder, folder), exist_ok=True)

print("Folder Structure Created Successfully!")

Folder Structure Created Successfully!

In [8]:
fake = Faker("en_IN")

print(fake.name())
print(fake.company())

Zehaan Contractor
Rattan and Sons

In [9]:
meeting_data = []

departments = [
    "HR",
    "Sales",
    "Marketing",
    "Finance",
    "IT",
    "Operations"
]

status = [
    "Completed",
    "Scheduled",
    "Cancelled"
]

for i in range(1, 101):

    meeting = {

        "Meeting_ID": f"MT{i:03}",

        "Meeting_Date":
        datetime.today() + timedelta(days=randint(-30,30)),

        "Meeting_Time":
        f"{randint(9,18)}:{choice(['00','30'])}",

        "Client_Name":
        fake.company(),

        "Department":
        choice(departments),

        "Agenda":
        choice([
            "Project Review",
            "Client Discussion",
            "Sales Pitch",
            "Budget Meeting",
            "Weekly Sync",
            "Vendor Discussion"
        ]),

        "Duration_Minutes":
        randint(30,120),

        "Status":
        choice(status),

        "Location":
        choice([
            "Conference Room A",
            "Conference Room B",
            "Zoom",
            "Google Meet"
        ])

    }

    meeting_data.append(meeting)

meeting_df = pd.DataFrame(meeting_data)

meeting_df.head()

,Meeting_ID,Meeting_Date,Meeting_Time,Client_Name,Department,Agenda,Duration_Minutes,Status,Location
0,MT001,2026-07-06 20:21:07.232572,9:30,"Dhar, Mahajan and Kara",Finance,Budget Meeting,91,Completed,Google Meet
1,MT002,2026-07-08 20:21:07.232746,12:00,Johal-Ramaswamy,Marketing,Weekly Sync,47,Completed,Zoom
2,MT003,2026-07-08 20:21:07.232838,9:30,Datta-Nigam,Sales,Sales Pitch,118,Cancelled,Google Meet
3,MT004,2026-06-22 20:21:07.232917,14:30,Nazareth-Zacharia,Operations,Vendor Discussion,84,Completed,Zoom
4,MT005,2026-06-05 20:21:07.232994,11:00,Soni-Goel,HR,Weekly Sync,94,Scheduled,Conference Room A

In [10]:
meeting_file = os.path.join(
    project_folder,
    "data",
    "meetings.xlsx"
)

meeting_df.to_excel(meeting_file, index=False)

print("Meeting Tracker Saved")

Meeting Tracker Saved

In [11]:
priority = [
    "High",
    "Medium",
    "Low"
]

task_status = [
    "Open",
    "In Progress",
    "Completed",
    "Pending"
]

owners = [
    "Kuldeep",
    "Rohan",
    "Anjali",
    "Neha",
    "Rahul"
]

task_data = []

for i in range(1,151):

    task = {

        "Task_ID": f"TSK{i:03}",

        "Task_Name":
        fake.sentence(nb_words=4),

        "Owner":
        choice(owners),

        "Priority":
        choice(priority),

        "Status":
        choice(task_status),

        "Start_Date":
        datetime.today() - timedelta(days=randint(1,20)),

        "Deadline":
        datetime.today() + timedelta(days=randint(1,30))

    }

    task_data.append(task)

task_df = pd.DataFrame(task_data)

task_df.head()

,Task_ID,Task_Name,Owner,Priority,Status,Start_Date,Deadline
0,TSK001,Ea error ducimus.,Kuldeep,Low,Completed,2026-06-26 20:21:38.438842,2026-07-14 20:21:38.438859
1,TSK002,Porro natus soluta aperiam eaque.,Rohan,Low,Completed,2026-06-12 20:21:38.438896,2026-07-08 20:21:38.438901
2,TSK003,Consectetur quam libero.,Rahul,Medium,Pending,2026-06-16 20:21:38.438926,2026-07-24 20:21:38.438967
3,TSK004,Quasi labore.,Anjali,Low,In Progress,2026-06-24 20:21:38.438997,2026-07-07 20:21:38.439000
4,TSK005,Tempore repudiandae ad sapiente dolor.,Kuldeep,Low,Completed,2026-06-14 20:21:38.439021,2026-07-02 20:21:38.439025

In [12]:
task_file = os.path.join(
    project_folder,
    "data",
    "tasks.xlsx"
)

task_df.to_excel(task_file,index=False)

print("Task Tracker Saved")

Task Tracker Saved

In [13]:
import os

data_folder = os.path.join(project_folder, "data")

print("Files in data folder:\n")

for file in os.listdir(data_folder):
    print(file)

Files in data folder:

meetings.xlsx
tasks.xlsx